apiVersion: v1
kind: Service
metadata:
  name: fault
  namespace: fault
  labels:
    app: fault
spec:
  type: NodePort
  selector:
    app: fault
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30280
      protocol: TCP
      name: http
